#!/bin/bash
# =============================================================================
# 02 - Hardening SSH (drop-in approach, cloud-init proof)
# =============================================================================
# Ten skrypt:
# 1. Tworzy drop-in /etc/ssh/sshd_config.d/00-hardening.conf
#    (alfabetycznie ostatni = wygrywa nad cloud-init 50-*, 60-*)
# 2. Wyłącza root login (PermitRootLogin no)
# 3. Wyłącza logowanie hasłem (wymusza klucze SSH)
# 4. Ustawia timeout nieaktywnej sesji
# 5. Ogranicza liczbę prób logowania
# 6. Wyłącza cloud-init regenerację SSH config (trwałe po restarcie)
# 7. Przy zmianie portu i aktywnym UFW: dopuszcza nowy port PRZED reloadem sshd
#    (inaczej użytkownik mógłby się odciąć - firewall blokowałby nowy port)
#
# DLACZEGO drop-in 00-* (NIE 99-*):
# OpenSSH stosuje "first wins" rule - PIERWSZE wystąpienie opcji wygrywa.
# Pliki w /etc/ssh/sshd_config.d/ ładowane są alfabetycznie. Cloud-init trzyma
# swoje ustawienia w 50-cloud-init.conf i 60-cloudimg-settings.conf. Drop-in
# musi być wczytany PRZED nimi, więc 00-hardening.conf wygrywa. Plus disable
# cloud-init ssh module = trwałe po restarcie.
#
# WAŻNE: Upewnij się że masz klucz SSH ZANIM wyłączysz logowanie hasłem!
# Test: zaloguj się z drugiego terminala kluczem PRZED zamknięciem tej sesji.
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC}  $1"; }
error() { echo -e "${RED}[X]${NC}  $1"; }

if [[ $EUID -ne 0 ]]; then
    error "Ten skrypt wymaga uprawnień root. Uruchom: sudo bash $0"
    exit 1
fi

echo "============================================"
echo "  Krok 2: Hardening SSH (drop-in 00-*)"
echo "============================================"
echo ""

# Effective port (uwzględnia drop-iny w sshd_config.d/)
# Zapisujemy output sshd -T do zmiennej żeby awk z exit nie wywołał SIGPIPE
# (z set -o pipefail to ubija skrypt).
SSHD_EFFECTIVE=$(sshd -T 2>/dev/null || true)
CURRENT_PORT=$(echo "$SSHD_EFFECTIVE" | awk '/^port / {print $2; exit}')
CURRENT_PORT=${CURRENT_PORT:-22}

echo "Aktualny port SSH (effective): $CURRENT_PORT"
echo ""

# --- Port SSH ---
# Env var HARDENING_SSH_PORT pozwala odpalić non-interactive
NEW_PORT="${HARDENING_SSH_PORT:-}"
if [[ -z "$NEW_PORT" ]]; then
    read -rp "Nowy port SSH (Enter = zostaw $CURRENT_PORT): " NEW_PORT
fi
NEW_PORT=${NEW_PORT:-$CURRENT_PORT}

if [[ "$NEW_PORT" -lt 1024 || "$NEW_PORT" -gt 65535 ]]; then
    if [[ "$NEW_PORT" -ne 22 ]]; then
        error "Port musi być w zakresie 1024-65535 (lub 22)."
        exit 1
    fi
fi

# --- Drop-in 00-hardening.conf ---
DROPIN="/etc/ssh/sshd_config.d/00-hardening.conf"
BACKUP="${DROPIN}.bak.$(date +%Y%m%d-%H%M%S)"

# Cleanup: jeśli istnieje stary 99-hardening.conf z poprzedniej wersji skryptu,
# usuń go (przed dodaniem drop-in 00-). OpenSSH stosuje "first wins" w sshd_config.d/
# - 99-* przegrywa z 50-cloud-init.conf, więc był nieskuteczny.
LEGACY_99="/etc/ssh/sshd_config.d/99-hardening.conf"
if [[ -f "$LEGACY_99" ]]; then
    rm -f "$LEGACY_99"
    info "Usunięto legacy $LEGACY_99 (zastąpiony przez 00-hardening.conf)"
fi

if [[ -f "$DROPIN" ]]; then
    cp "$DROPIN" "$BACKUP"
    info "Backup poprzedniego drop-in: $BACKUP"
fi

cat > "$DROPIN" <<EOF
# Hardening SSH - drop-in (alfabetycznie pierwszy = wygrywa "first-wins" rule)
# Generated by 02-harden-ssh.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# OpenSSH stosuje first-wins: pierwsze wystąpienie opcji wygrywa.
# 00-* < 50-cloud-init.conf < 60-cloudimg-settings.conf - więc 00-* wygrywa.
# Aby wyłączyć któryś setting - usuń lub zakomentuj poniżej.

Port $NEW_PORT
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
PermitEmptyPasswords no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
X11Forwarding no
MaxAuthTries 3
ClientAliveInterval 300
ClientAliveCountMax 2
EOF

chmod 600 "$DROPIN"
info "Drop-in zapisany: $DROPIN"
info "  - PermitRootLogin no"
info "  - PasswordAuthentication no (wymaga kluczy SSH)"
info "  - MaxAuthTries 3, X11 off, timeout 10 min"

# --- Cloud-init disable SSH regen (trwałe po restarcie) ---
CLOUD_OVERRIDE="/etc/cloud/cloud.cfg.d/99-disable-ssh-regen.cfg"
if [[ -d /etc/cloud/cloud.cfg.d ]]; then
    cat > "$CLOUD_OVERRIDE" <<'EOF'
# Wyłącz regenerację SSH config przez cloud-init.
# Hardening jest trzymany w /etc/ssh/sshd_config.d/00-hardening.conf
# i NIE może być nadpisywany przez cloud-init przy boot.
ssh_pwauth: false
disable_root: true
ssh_deletekeys: false
EOF
    chmod 644 "$CLOUD_OVERRIDE"
    info "Cloud-init override: $CLOUD_OVERRIDE"
else
    warn "Brak /etc/cloud/cloud.cfg.d - cloud-init nieobecny (OK, pomijam)."
fi

# --- Test config syntax ---
echo ""
if sshd -t 2>&1; then
    info "Konfiguracja SSH poprawna (sshd -t)."

    # --- UFW: dopuść nowy port PRZED reloadem sshd ---
    # Bez tego użytkownik z aktywnym UFW odciąłby się przy zmianie portu:
    # sshd zaczyna słuchać na nowym porcie, którego firewall jeszcze nie przepuszcza.
    # Celowo bez maskowania błędów - jeśli ufw allow padnie, set -e zatrzyma skrypt
    # ZANIM reload zmieni port.
    if [[ "$NEW_PORT" != "$CURRENT_PORT" ]] && command -v ufw >/dev/null 2>&1; then
        if ufw status 2>/dev/null | grep -q "^Status: active"; then
            ufw allow "$NEW_PORT/tcp"
            info "UFW: dopuszczono port $NEW_PORT/tcp (przed reloadem sshd)."
        fi
    fi

    # Reload zamiast restart - nie ubija aktywnych sesji
    if systemctl reload ssh 2>/dev/null; then
        info "SSH reload (aktywna sesja nieprzerwana)."
    elif systemctl reload sshd 2>/dev/null; then
        info "SSH reload (sshd)."
    else
        warn "Reload nieudany, próbuję restart..."
        systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null
        info "SSH restart wykonany."
    fi
else
    error "Błąd w konfiguracji SSH! Cofam zmiany."
    rm -f "$DROPIN"
    if [[ -f "$BACKUP" ]]; then
        cp "$BACKUP" "$DROPIN"
        info "Przywrócony backup: $BACKUP"
    fi
    error "Sprawdź ręcznie: sshd -t"
    exit 1
fi

# --- Verify effective config ---
echo ""
echo "=== Effective SSH config (po reload) ==="
SSHD_AFTER=$(sshd -T 2>/dev/null || true)
echo "$SSHD_AFTER" | grep -iE "^(port|permitrootlogin|passwordauthentication|pubkeyauthentication|maxauthtries|x11forwarding) " | sort
echo ""

# --- Firewall przypomnienie ---
# Nowy port jest dopuszczany w UFW automatycznie przed reloadem (patrz wyżej).
# Tutaj zostaje tylko sprzątanie starego portu + przypadek nieaktywnego UFW.
if [[ "$NEW_PORT" != "$CURRENT_PORT" ]]; then
    echo ""
    if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "^Status: active"; then
        warn "Stary port $CURRENT_PORT zamknij dopiero PO teście logowania na nowym:"
        echo "  sudo ufw delete allow $CURRENT_PORT/tcp  # po teście nowego portu"
    else
        warn "UFW nieaktywny - po jego włączeniu (krok 3) upewnij się, że port $NEW_PORT jest dopuszczony:"
        echo "  sudo ufw allow $NEW_PORT/tcp"
    fi
    echo ""
    warn "NIE zamykaj tego terminala dopóki nie zweryfikujesz logowania na nowym porcie!"
fi

info "SSH hardening zakończony."
echo ""
warn "Test w drugim terminalu PRZED zamknięciem tej sesji:"
echo "  ssh -p $NEW_PORT <user>@<server-ip>"
echo "Jeśli działa - bezpiecznie możesz zamknąć tę sesję."
echo ""
